apiVersion: batch/v1
kind: CronJob
metadata:
  name: kube-homelab-notifications-job
  namespace: homelab
spec:
  schedule: "*/1 * * * *"  # every 1 minute (K8s minimum granularity)
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: notion-writer
              image: curlimages/curl:latest
              imagePullPolicy: IfNotPresent
              env:
                - name: NOTION_DB_ID
                  value: "2168d9b5959f80bcb605d94e4d9294f1"
                - name: NOTION_USER_IDS
                  valueFrom:
                    secretKeyRef:
                      name: notion-notifications-userids-tmp
                      key: user-ids
                - name: NOTION_SECRET_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: notion-token-tmp
                      key: token
              command: ["/bin/sh", "-c"]
              args:
                - |
                PEOPLE_JSON=$(echo "$NOTION_USER_IDS" | awk -F',' '{for(i=1;i<=NF;i++) printf "{\"id\": \"%s\"}%s", $i, (i==NF ? "" : ",")}')
                NOW=$(date)
                curl -X POST "https://api.notion.com/v1/pages" \
                  -H "Authorization: Bearer $NOTION_SECRET_TOKEN" \
                  -H "Content-Type: application/json" \
                  -H "Notion-Version: 2022-06-28" \
                  -d '{
                    "parent": { "database_id": "'"$NOTION_DB_ID"'" },
                    "properties": {
                      "title": {
                        "title": [
                          {
                            "text": {
                              "content": "Argo Notification - '"$NOW"'"
                            }
                          }
                        ]
                      },
                      "Tags": {
                        "people": [
                          '"$PEOPLE_JSON"'
                        ]
                      }
                    }
                  }'
          restartPolicy: OnFailure