apiVersion: batch/v1
kind: CronJob
metadata:
  name: kube-homelab-notifications-job
  namespace: homelab
spec:
  schedule: "*/1 * * * *"  # every 1 minute (K8s minimum granularity)
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: notion-writer
              image: curlimages/curl:latest
              pullPolicy: IfNotPresent
              env:
                - name: NOTION_DB_ID
                  value: "2168d9b5959f80bcb605d94e4d9294f1"
                - name: NOTION_SECRET_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: notion-token-tmp
                      key: token
              command: ["/bin/sh", "-c"]
              args:
                - |
                  curl -v -X POST "https://api.notion.com/v1/pages" \
                    -H "Authorization: Bearer $NOTION_SECRET_TOKEN" \
                    -H "Content-Type: application/json" \
                    -H "Notion-Version: 2022-06-28" \
                    -d '{
                          "parent": { "database_id": "'$NOTION_DB_ID'" },
                          "properties": {
                            "Name": {
                              "title": [
                                {
                                  "text": {
                                    "content": "Argo Notification @Saurav Sahu - '"$(date)"'"
                                  }
                                }
                              ]
                            }
                          }
                        }'
          restartPolicy: OnFailure