apiVersion: v1
kind: Secret
metadata:
  name: notion-token-tmp
  namespace: homelab
type: Opaque
stringData:
  token: "<<TODO__DO_NOT_CHECKIN_NOTION_TOKEN>>"
---
apiVersion: v1
kind: Secret
metadata:
  name: notion-notifications-userids-tmp
  namespace: homelab
type: Opaque
stringData:
  user-ids: "<<TODO__DO_NOT_CHECKIN_NOTION_USER_ID>>"